// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx3TukgjBlnq6Qu8yAY8ibHEHKAIyj4aI',
    appId: '1:398848679909:web:209275e505aec5fa4e590c',
    messagingSenderId: '398848679909',
    projectId: 'sehatexpresss',
    authDomain: 'sehatexpresss.firebaseapp.com',
    storageBucket: 'sehatexpresss.firebasestorage.app',
    measurementId: 'G-D1GDZ624L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkI5XfhoOU0z9QBAHYlJhQmN9mUF_bgR4',
    appId: '1:398848679909:android:dfd0d17186eee8934e590c',
    messagingSenderId: '398848679909',
    projectId: 'sehatexpresss',
    storageBucket: 'sehatexpresss.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPkfUExEaQ096iYacIkKFuEbbuEnsWm1M',
    appId: '1:398848679909:ios:e582a1fde92651b54e590c',
    messagingSenderId: '398848679909',
    projectId: 'sehatexpresss',
    storageBucket: 'sehatexpresss.firebasestorage.app',
    iosClientId:
        '398848679909-753cgjf6fb8cp7hummrdd7cl3hf5lo4e.apps.googleusercontent.com',
    iosBundleId: 'com.sehatexpress.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPkfUExEaQ096iYacIkKFuEbbuEnsWm1M',
    appId: '1:398848679909:ios:e582a1fde92651b54e590c',
    messagingSenderId: '398848679909',
    projectId: 'sehatexpresss',
    storageBucket: 'sehatexpresss.firebasestorage.app',
    iosClientId:
        '398848679909-753cgjf6fb8cp7hummrdd7cl3hf5lo4e.apps.googleusercontent.com',
    iosBundleId: 'com.sehatexpress.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx3TukgjBlnq6Qu8yAY8ibHEHKAIyj4aI',
    appId: '1:398848679909:web:2a761f7fd6fe6d614e590c',
    messagingSenderId: '398848679909',
    projectId: 'sehatexpresss',
    authDomain: 'sehatexpresss.firebaseapp.com',
    storageBucket: 'sehatexpresss.firebasestorage.app',
    measurementId: 'G-5F6FETP2XW',
  );
}
